from datetime import datetime, timedelta
from decimal import Decimal
from math import isclose
from random import randint
from unittest.mock import patch

import pytest
from dateutil.relativedelta import relativedelta
from ddf import G
from django.test import TestCase, override_settings
from django.utils import timezone
from factory.faker import faker
from pytz import UTC
from rest_framework.exceptions import ValidationError
from rest_framework.reverse import reverse
from shared.django_apps.core.tests.factories import OwnerFactory, RepositoryFactory

from api.internal.chart.filters import apply_default_filters, apply_simple_filters
from api.internal.chart.helpers import (
    ChartQueryRunner,
    annotate_commits_with_totals,
    apply_grouping,
    validate_params,
)
from codecov.tests.base_test import InternalAPITest
from core.models import Commit
from utils.test_utils import Client

fake = faker.Faker()


def generate_random_totals(
    include_complexity=True, lines=None, hits=None, partials=None
):
    lines = lines or randint(5, 5000)
    hits = hits or randint(0, lines)
    partials = partials or randint(0, lines - hits)
    misses = lines - hits - partials
    coverage = (hits + partials) / lines
    complexity = randint(0, 5) if include_complexity else 0
    complexity_total = randint(complexity, 10) if include_complexity else 0

    totals = {
        "n": lines,
        "h": hits,
        "p": partials,
        "m": misses,
        "c": coverage,
        "C": complexity,
        "N": complexity_total,
        # Not currenly used: diff, files, sessions, branches, methods
    }
    return totals


def setup_commits(
    repo,
    num_commits,
    branch="main",
    start_date=None,
    meets_default_filters=True,
    **kwargs,
):
    """
    Generate random commits with different configurations, to accommodate different testing scenarios.

    :param repo: repo to associate the commits with
    :param num_commits: number of commits to create
    :param branch: branch to associate with the commit; randomly generated by DDF if none provided
    :param start_date: if provided, commit timestamp will be set to after this date.
    for more info on acceptable values for start_date, see: https://faker.readthedocs.io/en/master/providers/faker.providers.date_time.html#faker.providers.date_time.Provider.date_time_between
    :param meets_default_filters: when true the commit will meet all the conditions for the initial filtering done on commits
    :param kwargs: passed to generate_random_totals to manually set totals values
    """
    for _ in range(num_commits):
        timestamp = (
            fake.date_time_between(start_date=start_date, tzinfo=UTC)
            if start_date
            else fake.date_time(tzinfo=UTC)
        )

        totals = generate_random_totals(**kwargs) if meets_default_filters else None
        state = "complete" if meets_default_filters else "pending"
        ci_passed = True if meets_default_filters else False
        deleted = False if meets_default_filters else True

        G(
            Commit,
            repository=repo,
            branch=branch,
            timestamp=timestamp,
            totals=totals,
            state=state,
            ci_passed=ci_passed,
            deleted=deleted,
        )


def check_grouping_correctness(grouped_queryset, initial_queryset, data):
    """
    Used to test "apply_grouping" correctness. Programmatically verify that commits were grouped
    by the correct unit of time, and that within that grouping the correct commit was returned based on the
    query params provided.

    :param grouped_queryset: the queryset generated by calling "apply_grouping" on the initial_queryset
    :param initial_queryset: the annotated and filtered queryset provided to the apply_grouping call
    :param data: the grouping and filtering parameters that were applied when generating the grouping
    """
    grouping_unit = data.get("grouping_unit")
    agg_function = data.get("agg_function")
    agg_value = data.get("agg_value")

    """
    For each of the grouped commits, retrieve all the commits from the initial queryset that are within the same time window
    and verify that we can't find any that that better match the given aggregation function better.

    For example, if we grouped by max coverage per month, we'll get the commits for that month and verify that none of them have a coverage
    value greater than the grouped commit.
    """
    for commit in grouped_queryset:
        # Get the unit of time we grouped by so we can filter for all the commits in this commit's time window
        relative_delta_args = (
            {f"{grouping_unit}s": 1}
            if grouping_unit != "quarter"
            else {
                "months": 3
            }  # relativedelta doesn't except quarter as an argument so set that manually
        )

        # example: if agg_function is "min" and agg_value is "coverage", this will pass
        # "coverage__lt: <commit.coverage>" to the filter call below, to check if any commits in this window had lower coverage
        filtering_key = agg_value + ("__lt" if agg_function == "min" else "__gt")
        filtering_value_args = {filtering_key: getattr(commit, agg_value)}

        assert (
            not initial_queryset.filter(
                timestamp__gt=commit.truncated_date,
                timestamp__lt=commit.truncated_date
                + relativedelta(**relative_delta_args),
                repository__name=commit.repository.name,
            )
            .filter(
                **filtering_value_args
            )  # make two filter calls to avoid potentially filtering by timestamp multiple time in the same call which makes django unhappy
            .exclude(commitid=commit.commitid)
            .exists()
        )


class CoverageChartHelpersTest(TestCase):
    def setUp(self):
        self.org1 = OwnerFactory(username="org1")
        self.repo1_org1 = RepositoryFactory(author=self.org1, name="repo1")
        setup_commits(self.repo1_org1, 10)

        self.repo2_org1 = RepositoryFactory(author=self.org1, name="repo2")
        setup_commits(self.repo2_org1, 10)

        self.org2 = OwnerFactory(username="org2", service_id=1239128)
        self.repo1_org2 = RepositoryFactory(author=self.org2, name="repo1")
        setup_commits(self.repo1_org2, 10)

        self.user = OwnerFactory(
            organizations=[self.org1.ownerid],
            permission=[
                self.repo1_org1.repoid,
                self.repo2_org1.repoid,
                self.repo1_org2.repoid,
            ],
        )

    def test_apply_grouping(self):
        with self.subTest("min coverage"):
            setup_commits(self.repo1_org1, 20, start_date="-7d")

            data = {
                "owner_username": self.org1.username,
                "grouping_unit": "day",
                "agg_function": "min",
                "agg_value": "coverage",
                "start_date": (timezone.now() - relativedelta(days=7)).isoformat(),
                "end_date": timezone.now().isoformat(),
                "repositories": [self.repo1_org1.name],
            }

            initial_queryset = annotate_commits_with_totals(
                apply_simple_filters(
                    apply_default_filters(Commit.objects.all()), data, self.user
                )
            )
            grouped_queryset = apply_grouping(initial_queryset, data)
            check_grouping_correctness(grouped_queryset, initial_queryset, data)

        with self.subTest("max coverage"):
            setup_commits(self.repo1_org1, 20, start_date="-180d")

            data = {
                "owner_username": self.org1.username,
                "grouping_unit": "month",
                "agg_function": "max",
                "agg_value": "coverage",
                "start_date": (timezone.now() - relativedelta(months=6)).isoformat(),
                "end_date": timezone.now().isoformat(),
                "repositories": [self.repo1_org1.name],
            }

            initial_queryset = annotate_commits_with_totals(
                apply_simple_filters(
                    apply_default_filters(Commit.objects.all()), data, self.user
                )
            )
            grouped_queryset = apply_grouping(initial_queryset, data)
            check_grouping_correctness(grouped_queryset, initial_queryset, data)

        with self.subTest("min complexity"):
            setup_commits(self.repo1_org1, 20, start_date="-7d")

            data = {
                "owner_username": self.org1.username,
                "grouping_unit": "day",
                "agg_function": "max",
                "agg_value": "complexity",
                "start_date": (timezone.now() - relativedelta(days=7)).isoformat(),
                "end_date": timezone.now().isoformat(),
                "repositories": [self.repo1_org1.name],
            }

            initial_queryset = annotate_commits_with_totals(
                apply_simple_filters(
                    apply_default_filters(Commit.objects.all()), data, self.user
                )
            )
            grouped_queryset = apply_grouping(initial_queryset, data)
            check_grouping_correctness(grouped_queryset, initial_queryset, data)

        with self.subTest("max complexity"):
            setup_commits(self.repo1_org1, 20, start_date="-7d")

            data = {
                "owner_username": self.org1.username,
                "grouping_unit": "day",
                "agg_function": "max",
                "agg_value": "complexity",
                "start_date": (timezone.now() - relativedelta(days=7)).isoformat(),
                "end_date": timezone.now().isoformat(),
                "repositories": [self.repo1_org1.name],
            }

            initial_queryset = annotate_commits_with_totals(
                apply_simple_filters(
                    apply_default_filters(Commit.objects.all()), data, self.user
                )
            )
            grouped_queryset = apply_grouping(initial_queryset, data)
            check_grouping_correctness(grouped_queryset, initial_queryset, data)

    def test_ordering(self):
        with self.subTest("order by increasing dates"):
            data = {
                "organization": self.org1.username,
                "grouping_unit": "day",
                "agg_function": "min",
                "coverage_timestamp_ordering": "increasing",
                "agg_value": "coverage",
                "repositories": [self.repo1_org1.name],
            }

            queryset = annotate_commits_with_totals(
                apply_simple_filters(
                    apply_default_filters(Commit.objects.all()), data, self.user
                )
            )
            queryset = apply_grouping(queryset, data)

            results = queryset.values()
            # -1 because the last result doesn't need to be tested against
            for i in range(len(results) - 1):
                assert results[i]["timestamp"] < results[i + 1]["timestamp"]

        with self.subTest("order by decreasing dates"):
            data = {
                "organization": self.org1.username,
                "grouping_unit": "day",
                "agg_function": "min",
                "coverage_timestamp_ordering": "decreasing",
                "agg_value": "coverage",
                "repositories": [self.repo1_org1.name],
            }

            queryset = annotate_commits_with_totals(
                apply_simple_filters(
                    apply_default_filters(Commit.objects.all()), data, self.user
                )
            )
            queryset = apply_grouping(queryset, data)

            results = queryset.values()
            # -1 because the last result doesn't need to be tested against
            for i in range(len(results) - 1):
                assert results[i]["timestamp"] > results[i + 1]["timestamp"]


class TestChartQueryRunnerQuery(TestCase):
    """
    Tests for the querying-part of the ChartQueryRunner.
    """

    def setUp(self):
        self.org = OwnerFactory()
        self.repo1 = RepositoryFactory(author=self.org, active=True)
        self.repo2 = RepositoryFactory(author=self.org, active=True)
        self.repo3 = RepositoryFactory(author=self.org)
        self.repo4 = RepositoryFactory(author=self.org, active=True)
        self.user = OwnerFactory(
            permission=[
                self.repo1.repoid,
                self.repo2.repoid,
                self.repo3.repoid,
                self.repo4.repoid,
            ]
        )
        self.commit1 = G(
            model=Commit,
            repository=self.repo1,
            totals={"h": 100, "n": 120, "p": 10, "m": 10},
            branch=self.repo1.branch,
            state="complete",
        )
        self.commit2 = G(
            model=Commit,
            repository=self.repo2,
            totals={"h": 14, "n": 25, "p": 6, "m": 5},
            branch=self.repo2.branch,
            state="complete",
        )
        self.commit3 = G(
            model=Commit,
            repository=self.repo3,
            totals={"h": 14, "n": 25, "p": 6, "m": 5},
            branch=self.repo3.branch,
            state="complete",
        )

    @override_settings(GITHUB_CLIENT_ID="3d44be0e772666136a13")
    @pytest.mark.skip(
        reason="flaky, skipping since we're moving away from ChartQueryRunner soon anyway"
    )
    def test_query_supports_reverse_ordering(self):
        self.commit1.timestamp = timezone.now() - timedelta(days=7)
        self.commit1.save()

        query_runner = ChartQueryRunner(
            user=self.user,
            request_params={
                "owner_username": self.org.username,
                "service": self.org.service,
                "start_date": str(timezone.now() - timedelta(days=1)),
                "grouping_unit": "day",
                "coverage_timestamp_ordering": "decreasing",
            },
        )

        results = query_runner.run_query()

        assert len(results) == 2
        assert results[0]["date"] > results[1]["date"]

    def test_query_doesnt_crash_if_no_commits(self):
        with self.subTest("no repos case"):
            self.org.repository_set.all().delete()
            ChartQueryRunner(
                user=self.user,
                request_params={
                    "owner_username": self.org.username,
                    "service": self.org.service,
                    "grouping_unit": "day",
                },
            ).run_query()

        with self.subTest("no commits case"):
            repo = RepositoryFactory(author=self.org)
            self.user.permission = [repo.repoid]
            self.user.save()
            ChartQueryRunner(
                user=self.user,
                request_params={
                    "owner_username": self.org.username,
                    "service": self.org.service,
                    "grouping_unit": "day",
                },
            ).run_query()


class TestChartQueryRunnerHelperMethods(TestCase):
    """
    Tests for the non-querying-parts of the ChartQueryRunner, such
    as validation and parameter transformation.
    """

    def setUp(self):
        self.org = OwnerFactory()
        self.user = OwnerFactory()

    def test_start_date(self):
        with self.subTest("returns parsed start date if supplied"):
            start_date = timezone.now()
            assert ChartQueryRunner(
                self.user,
                {
                    "owner_username": self.org.username,
                    "service": self.org.service,
                    "grouping_unit": "day",
                    "start_date": str(start_date),
                },
            ).start_date == datetime.date(start_date)

        with self.subTest("returns first_commit_date if not supplied"):
            repo = RepositoryFactory(author=self.org, active=True)
            self.user.permission = [repo.repoid]
            self.user.save()
            commit = G(
                model=Commit,
                repository=repo,
                branch=repo.branch,
                state="complete",
                timestamp=timezone.now() - timedelta(days=3),
            )
            assert ChartQueryRunner(
                self.user,
                {
                    "owner_username": self.org.username,
                    "service": self.org.service,
                    "grouping_unit": "day",
                },
            ).start_date == datetime.date(commit.timestamp)

    def test_end_date(self):
        with self.subTest("returns parsed end date if supplied"):
            end_date = timezone.now() - timedelta(days=7)
            assert ChartQueryRunner(
                self.user,
                {
                    "owner_username": self.org.username,
                    "service": self.org.service,
                    "grouping_unit": "day",
                    "end_date": str(end_date),
                },
            ).end_date == datetime.date(end_date)

        with self.subTest("returns timezone.now() if not supplied"):
            assert ChartQueryRunner(
                self.user,
                {
                    "owner_username": self.org.username,
                    "service": self.org.service,
                    "grouping_unit": "day",
                },
            ).end_date == datetime.date(timezone.now())


@patch("api.shared.permissions.RepositoryPermissionsService.has_read_permissions")
class RepositoryCoverageChartTest(InternalAPITest):
    def _retrieve(self, kwargs={}, data={}):
        return self.client.post(
            reverse("chart-coverage-repository", kwargs=kwargs),
            data=data,
            content_type="application/json",
        )

    def setUp(self):
        self.org1 = OwnerFactory()
        self.repo1_org1 = RepositoryFactory(author=self.org1)
        setup_commits(self.repo1_org1, 10, start_date="-4d")

        self.current_owner = OwnerFactory(
            service="github",
            organizations=[self.org1.ownerid],
            permission=[self.repo1_org1.repoid],
        )

        self.client = Client()
        self.client.force_login_owner(self.current_owner)

    # when "grouping_unit" is commit we just return all the commits with no grouping/aggregation

    def test_get_commits_with_time_grouping(self, mocked_get_permissions):
        data = {
            "branch": "main",
            "start_date": timezone.now() - timedelta(7),
            "end_date": timezone.now(),
            "grouping_unit": "day",
            "agg_function": "max",
            "agg_value": "coverage",
            "repositories": [self.repo1_org1.name],
        }

        kwargs = {"owner_username": self.org1.username, "service": "gh"}

        mocked_get_permissions.return_value = True
        response = self._retrieve(kwargs=kwargs, data=data)

        assert response.status_code == 200
        assert len(response.data["coverage"]) > 0
        assert len(response.data["complexity"]) > 0

    def test_get_commits_with_coverage_change(self, mocked_get_permissions):
        data = {
            "branch": "main",
            "start_date": timezone.now() - timedelta(7),
            "end_date": timezone.now(),
            "grouping_unit": "day",
            "agg_function": "max",
            "agg_value": "coverage",
            "repositories": [self.repo1_org1.name],
        }

        kwargs = {"owner_username": self.org1.username, "service": "gh"}

        mocked_get_permissions.return_value = True
        response = self._retrieve(kwargs=kwargs, data=data)

        assert response.status_code == 200

        assert len(response.data["coverage"]) > 1
        # Verify that the coverage change was properly computed
        for index in range(len(response.data["coverage"])):
            commit = response.data["coverage"][index]

            # First commit should always have change = 0 since it changed nothing
            if index == 0:
                assert commit["coverage_change"] == 0
            else:
                assert (
                    commit["coverage_change"]
                    == commit["coverage"]
                    - response.data["coverage"][index - 1]["coverage"]
                )


class TestOrganizationChartHandler(InternalAPITest):
    def setUp(self):
        self.org = OwnerFactory()
        self.repo1 = RepositoryFactory(author=self.org, active=True)
        self.repo2 = RepositoryFactory(author=self.org, active=True)
        self.current_owner = OwnerFactory(
            permission=[self.repo1.repoid, self.repo2.repoid]
        )
        self.commit1 = G(
            model=Commit,
            repository=self.repo1,
            totals={"h": 100, "n": 120, "p": 10, "m": 10},
            branch=self.repo1.branch,
            state="complete",
        )
        self.commit2 = G(
            model=Commit,
            repository=self.repo2,
            totals={"h": 14, "n": 25, "p": 6, "m": 5},
            branch=self.repo2.branch,
            state="complete",
        )
        self.client = Client()
        self.client.force_login_owner(self.current_owner)

    def _get(self, kwargs={}, data={}):
        return self.client.get(
            reverse("chart-coverage-organization", kwargs=kwargs),
            data=data,
            content_type="application/json",
        )

    def test_basic_success(self):
        response = self._get(
            kwargs={"owner_username": self.org.username, "service": self.org.service},
            data={
                "grouping_unit": "day",
                "repositories": [self.repo1.name, self.repo2.name],
            },
        )

        assert response.status_code == 200
        assert len(response.data["coverage"]) == 1
        assert response.data["coverage"][0]["total_hits"] == 114
        assert response.data["coverage"][0]["total_lines"] == 145
        assert response.data["coverage"][0]["total_misses"] == 15
        assert response.data["coverage"][0]["total_partials"] == 16
